name: sync
on:
  # workflow_dispatch:
  schedule:
    - cron: "0 20 * * *"
jobs:
  blog:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: npm install && npm run start
      - name: Commit files
        id: commit-files
        run: |
          if [ -n "$(git status --porcelain ACL4SSR_Online_Full_noADJ.ini)" ]; then
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add ACL4SSR_Online_Full_noADJ.ini
            git commit -m "Automatic update"
            echo "hasChange=true" >> $GITHUB_OUTPUT
          else
            echo "No changes detected"
          fi
      - name: Push changes
        uses: ad-m/github-push-action@master
        if: ${{ steps.commit-files.outputs.hasChange == 'true' }}
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: ${{ github.ref }}
